---
# MySQL Configuration

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes

- name: restart mysql
  service: name=mysqld state=restarted

- name: Creates database for WordPress
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_user: root
    login_password: "{{ wp_db_root }}"
  tags: [ mysql ]

- name: Create MySQL user for WordPress
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ wp_db_root }}"
  tags: [ mysql ]
