---
- name: Install MySQL, Nginx, and PHP-FPM
  hosts: all
  remote_user: root
  # remote_user: user
  # become: yes
  # become_method: sudo
  vars_files:
    - vars/wordpress_vault.yml
    - vars/nginx.yml

- name: Include a soft play
  import_playbook: play_soft.yml

- name: Include a db play
  import_playbook: play_db.yml

- name: Include a websrv play
  import_playbook: play_websrv.yml

- name: Include a test play
  import_playbook: play_tests.yml

- name: Include a backup play
  import_playbook: play_backup.yml
