---
- name: Install MySQL, Nginx, and PHP-FPM
  hosts: all
  remote_user: root
  # remote_user: user
  # become: yes
  # become_method: sudo
  vars_files:
    - vars/wordpress_vault.yml

  roles:
    - { role: websrv, tags: [ wordpress, mysql, php ] }
