---
- name: Test inventory
  hosts: all
  remote_user: root
  # remote_user: user
  # become: yes
  # become_method: sudo
  vars_files:
    - vars/wordpress_vault.yml
    - vars/nginx.yml

  roles:
    - { role: tests }
