---
- name: Configure MySQL
  hosts: all
  remote_user: root
  no_log: True
# remote_user: user
  # become: yes
  # become_method: sudo
  vars_files:
    - vars/wordpress_vault.yml

  roles:
    - { role: adduser, tags: [ adduser ] }
