---
- name: Configure MySQL, Nginx, and PHP-FPM wordpress
  hosts: all
  remote_user: root
  # remote_user: user
  # become: yes
  # become_method: sudo
  vars_files:
    - vars/wordpress_vault.yml
    - vars/nginx.yml

  roles:
    - { role: soft, tags: [ wordpress, mysql, php ] }
    - { role: db, tags: [ mysql ] }
    - { role: websrv, tags: [wordpress] }
    - { role: tests }
    - { role: backup }
