---
- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/"
    remote_src: yes
    creates: "/var/www/wordpress"
  tags: [ wordpress ]

- name: Install nginx
  apt: name=nginx state=present

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: Install php-fpm and deps
  apt:
    name: ['php', 'php-fpm', 'php-mysql', 'php-curl', 'php-common']
    state: latest
  tags: [ php ]

- name: Disable default pool
  command: mv /etc/php/8.1/fpm/pool.d/www.conf /etc/php/8.1/fpm/pool.d/www.disabled creates=/etc/php/8.1/fpm/pool.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration
  template: src=wordpress.conf dest=/etc/php/8.1/fpm/pool.d/
  notify: restart php8.1-fpm

- name: restart php8.1-fpm
  service: name=php8.1-fpm state=restarted

- name: Install Mysql package and deps
  apt: 
    name:
      - mariadb-server
      - python3-pymysql
    state: present
  tags: [ mysql ]
#- name: Create Mysql configuration file
#  template: src=my.cnf.j2 dest=/etc/my.cnf
#  notify:
#  - restart mysql

# MySQL Configuration

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes

- name: restart mysql
  service: name=mysqld state=restarted

- name: Creates database for WordPress
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_user: root
    login_password: "{{ wp_db_root }}"
  tags: [ mysql ]

- name: Create MySQL user for WordPress
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ wp_db_root }}"
  tags: [ mysql ]

# WordPress Configuration

- name: Set up wp-config
  template:
    src: "wp-config.php.j2"
    dest: "/var/www/wordpress/wp-config.php"
  tags: [ wordpress ]