name: deploy ansible

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
      with:
        targets: ""
    - name: Install yamllint
      run: sudo apt-get install yamllint
    - name: Run Ansible
      uses: ./.github/actions/ansible
      run: ./play.sh
#  deployAnsible:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v1
#    - uses: ./.github/actions/ansible
#      with: 
#        playbook: playbook.yml
#        inventory: localhost
